services:
  - type: web
    name: price-survey-api
    env: docker
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: pricesurveydb
    plan: free
    region: oregon

