spring:
  application:
    name: price-survey-app

  # Database configuration - will use DATABASE_URL from Render
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/pricesurveydb}
    username: ${DB_USERNAME:pricesurvey}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    table: schema_version

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

  security:
    user:
      password: disabled

# Server configuration
server:
  port: ${PORT:8080}
  compression:
    enabled: true
  tomcat:
    max-threads: 200
    min-spare-threads: 20

# Logging configuration
logging:
  level:
    com.pricesurvey: INFO
    org.springframework.security: INFO
    org.flywaydb: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# JWT configuration
jwt:
  secret: ${JWT_SECRET:supersecretkeythatisverylongandunguessable123456789}
  expiration: ${JWT_EXPIRATION:86400000}

# App configuration
app:
  admin:
    email: ${ADMIN_EMAIL:garvey@pricesurvey.com}
    password: ${ADMIN_PASSWORD:admin123}